# Generated by Django 5.2.17 on 2026-09-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilidadeModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno')], max_length=20)),
                ('slug', models.CharField(choices=[('financeiro', 'Gestão financeira'), ('portal-aluno', 'Portal do aluno'), ('automacao', 'Automação')], max_length=40)),
                ('visivel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Visibilidade de módulo',
                'verbose_name_plural': 'Visibilidades de módulo',
                'unique_together': {('papel', 'slug')},
            },
        ),
    ]
