# Generated by Django 5.2.17 on 2026-09-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilidadeEixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno'), ('gestor', 'Gestor')], max_length=20)),
                ('slug', models.CharField(choices=[('meus_alunos', 'Meus alunos'), ('alunos', 'Alunos'), ('equipamentos', 'Equipamentos'), ('tipos_sessao', 'Tipos de sessão'), ('planos', 'Planos')], max_length=40)),
                ('visivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Visibilidade de eixo',
                'verbose_name_plural': 'Visibilidades de eixo',
                'unique_together': {('papel', 'slug')},
            },
        ),
    ]
