# Generated by Django 5.2.17 on 2026-09-12 01:55

from django.db import migrations, models

SLUGS_ANTIGOS = ("equipamentos", "tipos_sessao", "planos")


def consolidar_em_cadastros(apps, schema_editor):
    """Antes de restringir os slugs válidos, dobra qualquer configuração
    de visibilidade que já existisse para os antigos eixos separados
    (equipamentos/tipos_sessao/planos) num único registro "cadastros" por
    papel — preservando o comportamento (oculto permanece oculto) em vez
    de silenciosamente voltar a mostrar tudo depois do deploy."""
    VisibilidadeEixo = apps.get_model("modulos", "VisibilidadeEixo")

    papeis_com_algum_oculto = set(
        VisibilidadeEixo.objects.filter(slug__in=SLUGS_ANTIGOS, visivel=False).values_list(
            "papel", flat=True
        )
    )
    for papel in papeis_com_algum_oculto:
        VisibilidadeEixo.objects.update_or_create(
            papel=papel, slug="cadastros", defaults={"visivel": False}
        )
    VisibilidadeEixo.objects.filter(slug__in=SLUGS_ANTIGOS).delete()


def reverter(apps, schema_editor):
    # Não há como recuperar com precisão a granularidade original; não faz nada.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_visibilidadeeixo'),
    ]

    operations = [
        migrations.RunPython(consolidar_em_cadastros, reverter),
        migrations.AlterField(
            model_name='visibilidadeeixo',
            name='slug',
            field=models.CharField(choices=[('meus_alunos', 'Meus alunos'), ('alunos', 'Alunos'), ('cadastros', 'Cadastros (equipamentos, tipos de sessão e planos)')], max_length=40),
        ),
    ]
