# Generated by Django 5.2.17 on 2026-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_alter_visibilidadeeixo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visibilidadeeixo',
            name='slug',
            field=models.CharField(choices=[('meus_alunos', 'Meus alunos'), ('alunos', 'Alunos'), ('cadastros', 'Cadastros (equipamentos, tipos de sessão e planos)'), ('evolucao', 'Minha evolução (avaliação física do aluno)')], max_length=40),
        ),
    ]
