# Generated by Django 5.2.17 on 2026-09-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='tiposessao',
            name='duracao_min',
            field=models.PositiveSmallIntegerField(help_text='Duração da sessão em minutos.', verbose_name='Duração (min)'),
        ),
    ]
