# Generated by Django 5.2.17 on 2026-09-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('modalidade', models.CharField(choices=[('recorrente', 'Recorrente (por semana)'), ('pacote', 'Pacote de sessões')], max_length=20)),
                ('sessoes_por_semana', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantidade_sessoes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('validade_dias', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipos_sessao', models.ManyToManyField(blank=True, related_name='planos', to='cadastros.tiposessao')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('sessoes_contratadas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sessoes_por_semana', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('suspensa', 'Suspensa')], default='ativa', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratacoes', to='cadastros.aluno')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratacoes', to='planos.plano')),
            ],
            options={
                'verbose_name': 'Contratação',
                'verbose_name_plural': 'Contratações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
