# Generated by Django 5.2.17 on 2026-09-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratacao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Plano assinado', 'verbose_name_plural': 'Planos assinados'},
        ),
    ]
