# Generated by Django 5.2.17 on 2026-09-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_aluno_observacoes_and_more'),
        ('planos', '0002_alter_contratacao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='contratacao',
            name='sessoes_contratadas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sessões contratadas'),
        ),
        migrations.AlterField(
            model_name='contratacao',
            name='sessoes_por_semana',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sessões por semana'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='quantidade_sessoes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantidade de sessões'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='sessoes_por_semana',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sessões por semana'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='tipos_sessao',
            field=models.ManyToManyField(blank=True, related_name='planos', to='cadastros.tiposessao', verbose_name='Tipos de sessão'),
        ),
    ]
