# Generated by Django 5.2.17 on 2026-09-11 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('massa_magra_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('braco_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('cintura_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('quadril_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('coxa_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='cadastros.aluno')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação física',
                'verbose_name_plural': 'Avaliações físicas',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
