# Generated by Django 5.2.17 on 2026-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('motivo', models.CharField(choices=[('manutencao', 'Manutenção'), ('limpeza', 'Limpeza'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Bloqueio de equipamento',
                'verbose_name_plural': 'Bloqueios de equipamento',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
            options={
                'verbose_name': 'Disponibilidade do professor',
                'verbose_name_plural': 'Disponibilidades dos professores',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=20)),
                ('detalhe', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento da sessão',
                'verbose_name_plural': 'Eventos da sessão',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('reserva_inicio', models.DateTimeField()),
                ('reserva_fim', models.DateTimeField()),
                ('prof_inicio', models.DateTimeField()),
                ('prof_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('faltou', 'Faltou')], default='agendada', max_length=20)),
                ('encaixe_manual', models.BooleanField(default=False)),
                ('justificativa', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['inicio'],
            },
        ),
    ]
