# Generated by Django 5.2.17 on 2026-09-11 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('cadastros', '0001_initial'),
        ('planos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosessao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='cadastros.aluno'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='contratacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='planos.contratacao'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessao',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='cadastros.equipamento'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='cadastros.professor'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='cadastros.tiposessao'),
        ),
        migrations.AddField(
            model_name='eventosessao',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.sessao'),
        ),
    ]
