# Generated by Django 5.2.17 on 2026-09-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueioequipamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeprofessor',
            name='hora_fim',
            field=models.TimeField(verbose_name='Hora de fim'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeprofessor',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de início'),
        ),
        migrations.AlterField(
            model_name='eventosessao',
            name='acao',
            field=models.CharField(max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
